### ISSUE TITLE
wiki: printing page via browser  is a mess

### ISSUE THREAD

**Issue by vitus-a** [foodcoops/foodsoft#557]
main text is overlapping with headers and footers.

**Comment by wvengen** [comment]
Thanks for your bug report, that would be good to improve (e.g. using a print stylesheet).
Are those headers and footers of the browser (page title, url and date), or other headers/footers?
It would be useful to include a generated PDF here.

**Comment by vitus-a** [comment]
Here is an example printed with firefox.
[foodsoft-wiki.pdf](https://github.com/foodcoops/foodsoft/files/2461718/foodsoft-wiki.pdf)

**Comment by wvengen** [comment]
Thanks for the sample. Maybe the Bootstrap we use doesn't work well with print.
I wonder what adding this to the page CSS would do in general. For me it seems to work in Firefox.

```css
@media print {
  body > .logo, body > .nav, body > .navbar, header, footer { display: none; }
}
@page {
  margin-top: 1.5cm;
  margin-bottom: 1.5cm;
}
```
