### ISSUE TITLE
From address on outgoing mail does not match sender and is rejected on welcome mail

### ISSUE THREAD

**Issue by decentral1se** [foodcoops/foodsoft#873]
I have a working mail server up at `mail.example.com` which has a `noreply@example.com` account setup for outgoing mail. I have `mail.example.com` relaying incoming mail to `order.example.com:2525`. I have the following configuration in the `app_config.yml`:

```yaml
  # email address to be used as sender
  email_sender: noreply@example.com

  # email address to be used as from
  email_from: noreply@example.com

  # domain to be used for reply emails
  reply_email_domain: order.example.com
```

When I create a new user and a welcome mail is sent, I expect the following:

- `sender`: noreply@example.com
- `from`: noreply@example.com
- `reply_to`: <...>@order.example.com

However, the `from` ends up as what I would expect to see as the `reply_to` field. I see the following logs:

> 2021-05-23T14:48:05.270276000Z mail_example_com_smtp.1.2ifbc9pa0unjd2zftp6sdug17@example | COM_DOCKER_SWARM_SERVICE_NAME=mail_example_com_smtp,IMAGE_NAME=mailu/postfix:master@sha256:65fcef4fdbd97339a83e1f826392d9af13d7ec6de0a0566c425dfb38e5720c02 May 23 14:48:05 mail postfix/smtpd[434]: NOQUEUE: reject: RCPT from static.XXX.XXX.XXX.XXX.clients.your-server.de[XXX.XXX.XXX.XXX]: 553 5.7.1 <example.bounce+foo=bar.net@order.example.com>: Sender address rejected: not owned by user noreply@example.com; from=<example.bounce+foo=bar.net@order.example.com> to=<foo@bar.net> proto=ESMTP helo=<mail.example.com>

The `from` field does not match the `sender` of `noreply@example.com` and is rejected. 

The error mail does get successfully sent.

This logic appears to be happening here:

https://github.com/foodcoops/foodsoft/blob/a9ca093eda525584b7b7de23fe7be15fa703abd3/app/mailers/mailer.rb#L140

Is it possible that the logic which generates the `from` and `reply_to` address is not working?

Other info:
- I've tried both latest master and 4.7.1
- I've tried both multicoop and single coop mode

Thanks in advance :+1:
